export default {
    ADD_NOTE: 'ADD_NOTE',
    DELETE_NOTE: 'DELETE_NOTE',
    EDIT_NOTE: 'EDIT_NOTE',
    SET_CURRENT_EDITABLE_NOTE: 'SET_CURRENT_EDITABLE_NOTE',
    RESET_NOTE: 'RESET_NOTE',
    TOGGLE_TOAST: 'TOGGLE_TOAST',
}
